
version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: studynotion_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=mongodb+srv://mohantyphanibhusan:eyddSHTvuYPyLJEY@studynotiondb.egbl5.mongodb.net/CompanyDatabase
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USER=mohantyphanibhusan@gmail.com
      - EMAIL_PASS=ygnnzolsvwxlnqap
      - CLOUDINARY_NAME=dwdffshqd
      - API_KEY=158173115974515
      - API_SECRET=5ToDbwGd91ilrDSDYLCcFJaCe6Y
      - CLOUDINARY_FOLDER=STUDYNOTION
      - JWT_SECRET=phaniBhusanMohanty
      - STRIPE_WEBHOOK_SECRET=whsec_BoaFrGHbyqbL81QVYP0tsRtgEeRIpwa5
      - STRIPE_SECRET_KEY=sk_test_51Pw5u7EYoCAeJ9s3ZW8w3uLjN2xbAIOp5sUoQdhX8MA2VPCYfsRBq0SyhIQDXCBwKk7EXqGzHxROH7YyOC6tJwCh00h4BbD6kR
      - ADMIN_EMAIL=mohantyphanibhusan@gmail.com
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studynotion_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=http://backend:4000/api/v1
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build
    depends_on:
      - backend
    command: npm start