
version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: studynotion_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - CLOUDINARY_FOLDER=${CLOUDINARY_FOLDER}
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studynotion_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=http://backend:4000/api/v1
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build
    depends_on:
      - backend
    command: npm start